# Generated by Django 5.1 on 2024-08-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_aboutus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
