# Generated by Django 5.1 on 2024-08-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_aboutus_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
