# Generated by Django 5.1 on 2024-08-24 16:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='toc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
