# Generated by Django 5.1 on 2024-08-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_content_alter_post_toc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoy_name',
            new_name='category_name',
        ),
    ]
